### ISSUE TITLE
Adjust automation. Pull request closed issue 7, but it needs to go to Test first

### ISSUE THREAD

**Issue by r3tec** [arizet-connect/signal-processor#18]
See https://docs.github.com/en/github/managing-your-work-on-github/adding-issues-and-pull-requests-to-a-project-board for guidance

**Comment by YulianaCarson** [comment]
![image](https://user-images.githubusercontent.com/68156919/92180725-c086b900-ee15-11ea-8821-03c73d01d924.png)
On the side under the project user can change statuses. Thank you, Alex, for creating a project. 
Closing it.
